for fish
madumlao/phpenv pull request #16
Opened 2017-07-26 02:06 UTC by hisayan

I want to use phpenv on fish shell.

2017-07-26 02:51 UTC, mizunashi-mana requested changes

2017-07-26 02:51 UTC, mizunashi-mana commented on libexec/phpenv-init
> +    profile='~/.profile'
default startup config path of fish-shell is `~/.config/fish/config.fish`

## See also

* fish document: http://fishshell.com/docs/current/tutorial.html#tut_startup
* rbenv code: https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-init#L61

2017-07-26 02:51 UTC, mizunashi-mana commented on libexec/phpenv-init
> +  echo 'set -gx PATH '${NDENV_ROOT}'/shims $PATH'
NDENV -> PHPENV

2017-07-26 02:51 UTC, mizunashi-mana commented on completions/phpenv.fish
> +for cmd in (anyenv commands)
Why do you need anyenv here?

2017-07-26 02:56 UTC, hisayan commented on libexec/phpenv-init
> +    profile='~/.profile'
sorry my mistake. thanks

2017-07-26 03:09 UTC, mizunashi-mana commented
Add this change: https://github.com/rbenv/rbenv/blob/755c820724162f22d01dd9be5ebf724cb9209c9a/libexec/rbenv-init#L73

2017-07-26 03:22 UTC, mizunashi-mana requested changes

2017-07-26 03:22 UTC, mizunashi-mana commented on libexec/phpenv-init
> +  echo 'set -gx PATH '${PHPENV_ROOT}'/shims $PATH'
Please, syncing quoted style such as: https://github.com/rbenv/rbenv/blob/755c820724162f22d01dd9be5ebf724cb9209c9a/libexec/rbenv-init#L89

2017-07-26 03:24 UTC, mizunashi-mana commented
Please, support phpenv function for fish, too.

## See also

* https://github.com/rbenv/rbenv/blob/755c820724162f22d01dd9be5ebf724cb9209c9a/libexec/rbenv-init#L111

2017-07-27 04:12 UTC, mizunashi-mana commented on libexec/phpenv-init
> +  echo 'set -gx PATH '${PHPENV_ROOT}'/shims $PATH'
@hisayan any update?

2017-07-27 07:17 UTC, mizunashi-mana approved these changes
@hisayan Thanks for changes

LGTM 👍

2017-07-27 08:11 UTC, hisayan commented
@mizunashi-mana  Thank you for your kindness.

2018-08-01 17:07 UTC, merged

2018-08-01 17:07 UTC, madumlao commented
Was long overdue, sorry bout that!